### ISSUE TITLE
[1.2.1] Mod conflict

### ISSUE THREAD

**Issue by Alyaqdhans** [MrUnknown404/ItemFavorites#1]
When you install (Item physic Full) with this mod and lock an item it is still can be dropped with the dropping key (Q), I think that's because of (Item physic Full) changes the default dropping system, the more time you hold the dropping key the further dropped item go.

To reproduce:
1. Install both mods. 
2. Lock an item and close inventory.
3. Press the dropping key (Q).

**Comment by MrUnknown404** [comment]
Oh fun, I'll look into it sometime today. Thanks for letting me know!

**Comment by MrUnknown404** [comment]
This should be fixed as of 1.2.2!

**Comment by Alyaqdhans** [comment]
Thanks. 
By the way, do you know where I can learn how to make a mod because I couldn't find on youtube or internet.
If you don't know any place, and also if you don't mind, can you make a mod (look for a mod called Visp, it's new) make it simple, one color like white highlight for new items is good and when you hover over the highlighted items it gets removed (minecraft 1.12.2).

**Comment by MrUnknown404** [comment]
Here's a decent tutorial I found real quick that may be helpful for creating your first mod. [Link](https://cubicoder.github.io/tutorials/1-12-2/tutorials/) (Hope that helps)
And as for me taking your request, I'll think about it if I have the time but I can't really guarantee anything. I'll let you know if I end up making it though.
