### ISSUE TITLE
[1.2.2] Another mod conflict

### ISSUE THREAD

**Issue by Alyaqdhans** [MrUnknown404/ItemFavorites#2]
To reproduce:
1. Install this mod with (Mouse tweaks).
2. Get 2 or more items in the inventory hot bar.
3. lock 1 item and hold the shift + left mouse button and start entering the items in a chest or inventory while holding both buttons move the mouse to all items until you reach the locked item and it will be entered too.

**Comment by MrUnknown404** [comment]
I'll look into it sometime soon! Thanks for letting me know!

**Comment by MrUnknown404** [comment]
I've been looking for a few hours now and I can't really figure out how to fix this.
I'll keep this issue open for now

**Comment by Alyaqdhans** [comment]
I have been thinking about it, that what it could be because you use 2 buttons and moving mouse.
But I don't know anything in java script, so I can't think of anything inside the mod.
Anyways, whenever you feel free just put some time on it I know you can figure it out 👍
