### ISSUE TITLE
[1.2.2] Sorting inventory

### ISSUE THREAD

**Issue by Alyaqdhans** [MrUnknown404/ItemFavorites#3]
If you use (Quark) or (Inventory Tweaks) to sort inventory, the locked item will be moved but the lock stays at the same slot.

**Comment by MrUnknown404** [comment]
Thanks for letting me know! I'll look into it soon.

**Comment by MrUnknown404** [comment]
Did you encounter this problem with quark or inventory tweaks? Because I thought I fixed this problem with inventory tweaks. And if its quark, doesn't quark already have a favorite system built in?

**Comment by Alyaqdhans** [comment]
My problem were on quark and no it doesn't have favorite system (It adds sorting button in the inventory, but if you installed Inventory Tweaks with it it gets removed). Also, by fixing Inventory Tweaks you mean the lock get removed if you sort the inventory? Isn't it supposed to lock the item from moving?

**Comment by MrUnknown404** [comment]
It should lock the item from moving, does it not do that? I guess I'll check in the morning.

**Comment by MrUnknown404** [comment]
![20210201_041005](https://user-images.githubusercontent.com/26510180/106451176-69782500-6443-11eb-8cfa-aaf6c410d215.jpg)
According to quarks website it exists but I don't know how it works so I guess I'll test that too tomorrow

**Comment by Alyaqdhans** [comment]
I didn't know quark has this. Maybe because it's Alt + right click made me not noticing about it.

**Comment by Alyaqdhans** [comment]
I tried it and it only locks the item from being deposited by the quark buttons and it adds a star symbol to the name.
![Screenshot (26)](https://user-images.githubusercontent.com/58079015/106453240-6bbd9c00-64a2-11eb-82bc-2b491de12645.png)
![Screenshot (27)](https://user-images.githubusercontent.com/58079015/106453300-842db680-64a2-11eb-8429-f21e899c3b2c.png)
